# Generated by Django 5.2.5 on 2025-08-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('weather_alert', 'Weather Alert'), ('daily_forecast', 'Daily Forecast'), ('test_message', 'Test Message'), ('other', 'Other')], max_length=50)),
                ('sms_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS alerts', max_length=20, null=True)),
                ('default_city', models.CharField(default='London', max_length=100)),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1)),
                ('wind_speed_unit', models.CharField(choices=[('m/s', 'm/s'), ('km/h', 'km/h'), ('mph', 'mph')], default='m/s', max_length=5)),
                ('pressure_unit', models.CharField(choices=[('hPa', 'hPa'), ('inHg', 'inHg')], default='hPa', max_length=4)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('storm_alerts', models.BooleanField(default=True)),
                ('heat_alerts', models.BooleanField(default=True)),
                ('cold_alerts', models.BooleanField(default=True)),
                ('flood_alerts', models.BooleanField(default=True)),
                ('air_quality_alerts', models.BooleanField(default=True)),
                ('daily_forecast', models.BooleanField(default=False)),
                ('severe_weather_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('alert_types', models.JSONField(default=list, help_text='List of alert types to receive')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Subscription',
                'verbose_name_plural': 'Alert Subscriptions',
                'unique_together': {('user', 'city')},
            },
        ),
    ]
