# Generated by Django 5.2.5 on 2025-08-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlertSubscription',
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
